name: "POE Display"
description: "Drives the SSD1306 OLED on the Waveshare PoE HAT B"
version: "1.0.8"
slug: "poe_display"
hassio_role: manager
hassio_api: true
init: false
arch:
  - aarch64
devices:
  - /dev/i2c-1
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.21
options: {}
schema: {}
